<<<<<<< HEAD
version: 2.1
orbs:
  node: circleci/node@4.7.0
    
jobs:
      build:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run build
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
      test:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run test
              name: Test app
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
      eslint:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run lint
              name: Lint app
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
workflows:
      on_commit:
        jobs:
          #- build
          - test
=======
version: 2.1
orbs:
  node: circleci/node@4.7.0
    
jobs:
      build:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run build
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
      test:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run test
              name: Test app
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
      eslint:
        docker:
          - image: cimg/node:17.2.0
        steps:
          - checkout
          - node/install-packages:
              pkg-manager: npm
          - run:
              command: npm run lint
              name: Lint app
          - persist_to_workspace:
              root: ~/project
              paths:
                - .
workflows:
      on_commit:
        jobs:
          - build
          #- test
>>>>>>> 8d80f80569a173985a91154898a169e9de66122c
